policies:
  - type: commit
    spec:
      conventional:
        types:
          - "ci"
          - "build"
          - "chore"
          - "docs"
          - "style"
          - "refactor"
          - "perf"
          - "test"
